### ISSUE TITLE
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

### ISSUE THREAD

**Issue by Pablo849** [trbs/rfc3161ng#16]
File "/Users/MacBook/Proyectos/env-parques/lib/python3.4/site-packages/rfc3161ng/api.py", line 253, in __call__
    base64string = base64.standard_b64encode(b'%s:%s' % (username, password))
TypeError: unsupported operand type(s) for %: 'bytes' and 'tuple'

When I try to connect with username and password
Python: 3.4.4

**Comment by trbs** [comment]
This is because % string formatting is not supported in python 3 prior to 3.5. Solution is to upgrade to 3.5 or later :)
