### ISSUE TITLE
Package for Debian?

### ISSUE THREAD

**Issue by petterreinholdtsen** [trbs/rfc3161ng#3]
Hi.  It would be great if this package was available from Debian as an official package.  Are you interested in helping to make it happen?  I've started the process by creating https://bugs.debian.org/909002 .

**Comment by petterreinholdtsen** [comment]
I created Debian packaging in https://salsa.debian.org/pere/python-rfc3161ng and uploaded a patch into the NEW queue.  It would be great if you could have a look at the pull requests and make a new release fairly soon.

**Comment by trbs** [comment]
Thanks ! and happy to merge Debian packaging patch here

**Comment by petterreinholdtsen** [comment]
Thank you for your quick response.  It make it a lot easier to take on the maintenance burden in Debian to know I have someone who understand the code with me. :)

**Comment by trbs** [comment]
I think we can close this issue right ? You suggested to keep the `debian/` directory separate from this repository. (Still happy to merge that in btw if it makes sense :-) )

**Comment by petterreinholdtsen** [comment]
I am fine with cosing this issue, absolutely.  I plan to upload a new version to Debian as soon as you tag a new release. Do you have any new release planned?

**Comment by trbs** [comment]
here you go :-) e546212920f0681a3e29c8f987adf2531a2e73a6

**Comment by petterreinholdtsen** [comment]
[trbs]
> here you go :-) e546212920f0681a3e29c8f987adf2531a2e73a6

Thank you.  I'm wrapping up a new upload.

Note:

% nosetests3 tests/test_api.py
Using configuration from /usr/lib/ssl/openssl.cnf
Verification: OK
......E
======================================================================
ERROR: test_api.test_generalized_time_decoding
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/pere/src/bitmynt/deb/python-rfc3161ng-salsa/tests/test_api.py", line 120, in test_generalized_time_decoding
    assert generalizedtime_to_utc_datetime('20180208181004.948468-01', False) == datetime.datetime(2018, 2, 8, 19, 10, 4, 948468, tzinfo=dateutil.tz.tzutc())
  File "/home/pere/src/bitmynt/deb/python-rfc3161ng-salsa/rfc3161ng/api.py", line 83, in generalizedtime_to_utc_datetime
    dt = dt.replace(tzinfo=dateutil.tz.tzoffset(name, diff if d['tz'][0] == '+' else -diff))
  File "/usr/lib/python3/dist-packages/dateutil/tz/tz.py", line 60, in __init__
    self._offset = datetime.timedelta(seconds=offset)
TypeError: unsupported type for timedelta seconds component: datetime.timedelta

----------------------------------------------------------------------
Ran 7 tests in 2.159s

FAILED (errors=1)

Btw, is it intentional no 2.1.0 entry in CHANGELOG?

-- 
Happy hacking
Petter Reinholdtsen

**Comment by trbs** [comment]
Updated changelog

**Comment by petterreinholdtsen** [comment]
Happy to report the Debian package was accepted into the archive today. http://tracker.debian.org/pkg/python-rfc3161ng

**Comment by trbs** [comment]
awesome !
