### ISSUE TITLE
Please document specific licensing terms

### ISSUE THREAD

**Issue by petterreinholdtsen** [trbs/rfc3161ng#6]
The only information about the license is in setup.py, stating 'MIT'.  Please add a file with the exact terms in the repository.  It would be extra helpful if you could add copyright information at the top of each source file too.

**Comment by petterreinholdtsen** [comment]
A list of MIT license variations can be found on https://en.wikipedia.org/wiki/MIT_License#Various_versions .  Perhaps the Expat license is the wanted one?

**Comment by trbs** [comment]
It’s hard to say what the exact MIT license was as intended by the original authors. 

I will add a license file to make this clearer.
